---
- name: "Provision Server"
  hosts: all
  user: root

  tasks:
    - name: "Updates everything"
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
      register: apt_output

    - name: "APT stdout"
      ansible.builtin.debug:
        var: apt_output.stdout_lines

    - name: "APT stderr"
      ansible.builtin.debug:
        var: apt_output.stderr_lines

    - name: "Check if a reboot is needed"
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: false
      register: reboot_required_file

    - name: Reboot the box if kernel updated
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
