FROM alpine:3 as native-image-backend-builder
WORKDIR /app
# https://bell-sw.com/pages/downloads/native-image-kit/
RUN wget https://download.bell-sw.com/vm/23.1.2/bellsoft-liberica-vm-core-openjdk21.0.2+14-23.1.2+1-linux-x64-musl.apk
RUN wget -P /etc/apk/keys/ https://apk.bell-sw.com/info@bell-sw.com-5fea454e.rsa.pub
RUN apk add ./bellsoft-liberica-vm-core-openjdk21.0.2+14-23.1.2+1-linux-x64-musl.apk
ENV PATH="/opt/bellsoft/liberica-vm-core-23.1.2-openjdk21/bin:${PATH}"
RUN apk add build-base zlib-dev fontconfig-dev freetype-dev
COPY .mvn .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:resolve
COPY src/main ./src/main
COPY src/test ./src/test
RUN ./mvnw -Pnative native:compile

FROM alpine:3
WORKDIR /app
RUN apk add fontconfig-dev freetype-dev
COPY --from=native-image-backend-builder /app/target/DRLLeaderboardBackend /app/DRLLeaderboardBackend
RUN chmod +x /app/DRLLeaderboardBackend
ENTRYPOINT ["/app/DRLLeaderboardBackend"]
