version: '3'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: drl
    shm_size: '512m'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - local_network
    command: ["postgres", "-c", "log_statement=all"]

networks:
  local_network:
