version: '3.8'
services:
  backend:
    build:
        context: ../../../
        dockerfile: src/docker/local/Dockerfile-backend
    env_file:
      - docker_compose.env
#      - docker_compose_no_data_updaters.env
    ports:
      - "8080:8080"
    volumes:
      - ../../../../logs/backend:/var/log/backend
      - ../../../../logs/gc_backend:/var/log/gc_backend
      - ../../../../logs/heapdumps_backend:/var/log/heapdumps_backend
    networks:
      - local_network
    stop_grace_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G

networks:
  local_network:
