FROM node:18-alpine as frontend-builder
WORKDIR /app
COPY frontend/.yarn .yarn/
COPY frontend/.yarnrc.yml frontend/package.json frontend/yarn.lock ./
RUN yarn install
COPY frontend/public public/
COPY frontend/src src/
COPY frontend/env env/
COPY frontend/.eslintignore frontend/.eslintrc.cjs frontend/.npmrc \
    frontend/.pnp.cjs frontend/.pnp.loader.mjs frontend/index.html frontend/jsconfig.json \
    frontend/postcss.config.cjs frontend/quasar.config.js frontend/purgecss.config.cjs ./

FROM frontend-builder as frontend-builder-local
WORKDIR /app
# TODO deactivate purge for now, because it removes too much
#RUN yarn quasar build && yarn purgecss --config ./purgecss.config.cjs
RUN rm env/.env.prod && mv env/.env.dev env/.env.prod
RUN yarn quasar build

FROM nginx:latest
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=frontend-builder-local /app/dist/spa /www/leaderboard
