services:
  thumbor:
    image: thumbororg/thumbor:7.5-py-3.11
#    ports:
#      - "8888:8888"
    command: [
      "--conf", "/home/thumbor/thumbor.conf",
#      "-l", "debug"
    ]
    volumes:
      - ../../../imgcache/result-storage:/home/thumbor/imgcache/result-storage
      - ../../../imgcache/source-storage:/home/thumbor/imgcache/source-storage
      - ./thumbor.conf:/home/thumbor/thumbor.conf
    networks:
      - local_network
  nginx:
    build:
      context: ../../../../
      dockerfile: backend/src/docker/local/Dockerfile-nginx+frontend
    ports:
      - "8888:80"
      - "4443:443"
    volumes:
      - ./nginx-app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
        max-size: 5m
    command: >-2
      /bin/sh -c '
      nginx -g "daemon off;"'
    networks:
      - local_network
networks:
  local_network:
