services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: drl
    networks:
      - local_network
    command: ["postgres", "-c", "log_statement=all"]
  backend:
    build:
      context: ../../../
      dockerfile: src/docker/local/Dockerfile-backend
    env_file:
      - docker_compose.env
      - docker_compose_no_data_updaters.env
    ports:
      - "8080:8080"
    volumes:
      - ../../../logs/backend:/var/log/backend
      - ../../../logs/gc_backend:/var/log/gc_backend
      - ../../../logs/heapdumps_backend:/var/log/heapdumps_backend
    networks:
      - local_network
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 800M
  nginx:
    build:
      context: ../../../../
      dockerfile: backend/src/docker/local/Dockerfile-nginx+frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
        max-size: 5m
    command: >-2
      /bin/sh -c '
      nginx -g "daemon off;"'
    networks:
      - local_network
  thumbor:
    image: thumbororg/thumbor:7.5-py-3.11
    ports:
      - "8888:8888"
    command: [
      "--conf", "/home/thumbor/thumbor.conf",
      "-l", "debug"
    ]
    volumes:
      - ../../../imgcache/result-storage:/home/thumbor/imgcache/result-storage
      - ../../../imgcache/source-storage:/home/thumbor/imgcache/source-storage
      - ./thumbor.conf:/home/thumbor/thumbor.conf
    networks:
      - local_network
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 70M

networks:
  local_network:
