#docker build --tag native-test:v1 $(./build_docker_args.sh) -f Dockerfile_native_image_test ..
#docker run --rm --network local_local_network -p 8080:8080 native-test:v1
#docker run --rm -it --network local_local_network -p 8080:8080 native-test:v1 sh
FROM alpine:3 as native-image-backend-builder
WORKDIR /app
# https://bell-sw.com/pages/downloads/native-image-kit/
RUN wget https://download.bell-sw.com/vm/23.1.2/bellsoft-liberica-vm-core-openjdk21.0.2+14-23.1.2+1-linux-x64-musl.apk
RUN wget -P /etc/apk/keys/ https://apk.bell-sw.com/info@bell-sw.com-5fea454e.rsa.pub
RUN apk add ./bellsoft-liberica-vm-core-openjdk21.0.2+14-23.1.2+1-linux-x64-musl.apk
ENV PATH="/opt/bellsoft/liberica-vm-core-23.1.2-openjdk21/bin:${PATH}"
RUN apk add build-base zlib-dev fontconfig-dev freetype-dev
COPY backend/.mvn .mvn
COPY backend/mvnw backend/pom.xml ./
RUN ./mvnw dependency:resolve
COPY backend/src/main ./src/main
COPY backend/src/test ./src/test
RUN ./mvnw -Pnative native:compile

FROM alpine:3 as native-image-runner
WORKDIR /app
RUN apk add fontconfig-dev freetype-dev
COPY --from=native-image-backend-builder /app/target/DRLLeaderboardBackend /app/DRLLeaderboardBackend
RUN chmod +x /app/DRLLeaderboardBackend
ENV SPRING_DATASOURCE_URL="jdbc:postgresql://postgres:5432/drl?reWriteBatchedInserts=true"
ENTRYPOINT ["/app/DRLLeaderboardBackend"]
