services:
#  web:
#    build: ./flask_test
#    ports:
#      - "8080:5000"
#    networks:
#      - local_network
#  redis:
#    image: "redis:alpine"
#    networks:
#      - local_network
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: drl
    networks:
      - local_network
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - /var/log/backend:/var/log
    networks:
      - local_network
    depends_on:
      - postgres
  nginx:
    image: nginx:latest
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/conf.d:/etc/nginx/conf.d
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    logging:
      options:
        max-size: 5m
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - local_network
  certbot:
    image: certbot/certbot:latest
    pull_policy: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - local_network

networks:
  local_network:
