services:
#  web:
#    build: ./flask_test
#    ports:
#      - "8080:5000"
#    networks:
#      - local_network
#  redis:
#    image: "redis:alpine"
#    networks:
#      - local_network
  postgres:
    image: postgres:15
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: drl
    networks:
      - local_network
    logging:
      options:
        max-size: 5m
  backend:
    build: ./backend
    env_file:
      - docker_compose.env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/log/backend:/var/log/backend
      - /var/log/gc_backend:/var/log/gc_backend
      - /var/log/heapdumps_backend:/var/log/heapdumps_backend
      - ./data/backend/imgcache:/imgcache
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - local_network
    depends_on:
      - postgres
    logging:
      options:
        max-size: 5m
  nginx:
    image: nginx:latest
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_conf/conf.d:/etc/nginx/conf.d
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./frontend:/www
    logging:
      options:
        max-size: 5m
    command: >-2
      /bin/sh -c '
      mkdir -p /etc/nginx/ssl;
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -batch;
      while :;
      do
        sleep 6h & wait $${!};
        nginx -s reload;
      done & nginx -g "daemon off;"'
    networks:
      - local_network
  certbot:
    image: certbot/certbot:latest
    pull_policy: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - local_network
    logging:
      options:
        max-size: 5m
  thumbor:
    image: thumbororg/thumbor:7.5-py-3.11
    ports:
      - "127.0.0.1:8888:8888"
    command: [
      "--conf", "/home/thumbor/thumbor.conf",
#      "-l", "debug"
    ]
    volumes:
      - ./data/imgcache/result-storage:/home/thumbor/imgcache/result-storage
      - ./data/imgcache/source-storage:/home/thumbor/imgcache/source-storage
      - ./thumbor/thumbor.conf:/home/thumbor/thumbor.conf
    networks:
      - local_network
    deploy:
      resources:
        limits:
          memory: 200M
    logging:
      options:
        max-size: 5m

networks:
  local_network:
