spring:
  lifecycle:
    timeout-per-shutdown-phase: 29s
  threads:
    virtual:
      enabled: true
  jackson:
    time-zone: UTC
#    serialization:
#      write_dates_as_timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/drl?reWriteBatchedInserts=true
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none # update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true
        type:
            json_format_mapper: de.gregord.drlleaderboardbackend.config.CustomHibernateJsonFormatter
    generate-ddl: false # true
    database: postgresql
  flyway:
    validateMigrationNaming: true
    locations: classpath:db/migration
  task:
    scheduling:
      pool:
        size: 3

management:
  endpoints:
    web.exposure.include: '*'
  server:
    port: 8081

app:
  name: DRLLeaderboardBackend
  version: 1.0.0
  description: DRLLeaderboardBackend
  frontend-url: https://drl-leaderboards.com
  drl-api:
    leaderboard-endpoint: "https://api.drlgame.com/leaderboards/?limit={limit}&game-type=Race&score-type=TimeMin&page={page}&token={token}&diameter=7&custom-physics=false&drl-official=true"
    maps-endpoint: "https://api.drlgame.com/maps?token={token}&page={page}&map-category=MapDRL&map-category=MapMultiGP&map-category=MapDRLSimCup&map-category=MapVirtualSeason&map-category=MapFeatured&limit=25"
    map-detail-endpoint: "https://api.drlgame.com/maps/{guid}?token={token}&guid={guid}&root=true"
    # In theory the limit is 200 for the map endpoint, but currently some track data is buggy
    # and then the drl api will throw an error, so we are crawling in smaller batches
    community-maps-endpoint: "https://api.drlgame.com/maps?token={token}&page={page}&sort=updated-at&order=desc&is-race-allowed=true&root=false&map-category=MapCommon&is-public=true&limit=25"
    tournament-endpoint: "https://api.drlgame.com/tournaments?token={token}&limit=12&minimum-skill=0"
    tournament-detail-endpoint: "https://api.drlgame.com/tournaments/{guid}?token={token}"
    duration-between-requests: 200ms

  data-updater:
    leaderboards:
      enabled: true
    tracks:
      cron: "0 0 */3 * * *" # every 3 hours
    tournaments:
      cron: "0 */1 * * * *" # every Minute (But waits for the previous run to finish)
    season:
      cron: "0 0 0 * * *"

server:
  shutdown: graceful
  error:
    include-message: always
    include-exception: false
    include-stacktrace: never
    include-binding-errors: always
  forward-headers-strategy: framework
  servlet:
    context-path: /api

logging:
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/backend/drl-api-crawler-%d{yyyy-MM-dd}.%i
      max-file-size: 2MB
      total-size-cap: 10MB
      max-history: 10
  level:
    root: info
    de.gregord.drlleaderboardbackend: info
#    org.cache2k: debug
#    org.springframework.cache: debug
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
#    ch.qos.logback: trace
#    org.springframework: debug
#    org.springframework.transaction: trace
#    org.hibernate.engine.transaction.internal.TransactionImpl: debug
#    org.springframework.orm.jpa: debug

