spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drl?reWriteBatchedInserts=true
  jpa:
    properties:
      hibernate:
        generate_statistics: false

app:
  show-sql: false
  drl-api:
    duration-between-requests: 200ms
  data-updater:
    leaderboards:
      enabled: true
    tracks:
      cron: "-" # disabled
    tournaments:
      cron: "-" # disabled

logging:
  logback:
    rollingpolicy:
      file-name-pattern: logs/drl-api-crawler-%d{yyyy-MM-dd}.%i
      clean-history-on-start: true

  level:
    root: info
    de.gregord.drlleaderboardbackend: debug
#    de.gregord.drlleaderboardbackend.services: error
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
#    org.springframework: trace
#    org.hibernate: trace
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
#    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
