spring:
  jackson:
    time-zone: UTC
#    serialization:
#      write_dates_as_timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/drl?reWriteBatchedInserts=true
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_updates: true
        order_inserts: true
    generate-ddl: true
    database: postgresql

management:
  endpoints:
    web.exposure.include: '*'
  server:
    port: 8081

app:
  name: DRLLeaderboardBackend
  version: 1.0.0
  description: DRLLeaderboardBackend
  drl-api:
    token: "[PASTE YOUR TOKEN HERE]"
    leaderboard-endpoint: "https://api.drlgame.com/leaderboards/?limit=20&game-type=Race&score-type=TimeMin&page={page}&token={token}&diameter=7&custom-physics=false&drl-official=true"
    maps-endpoint: "https://api.drlgame.com/maps?token={token}&page={page}&map-category=MapDRL&map-category=MapMultiGP&map-category=MapDRLSimCup&map-category=MapVirtualSeason&map-category=MapFeatured"
    # To finish within 10 minutes I need at least 1 request every 0.7 seconds = ~1.43 requests/s
#    duration-between-requests: 666ms # ~1.5 requests/s # Took 17 Minutes, because prod server is slower than my local machine
    duration-between-requests: 333ms # ~3 requests/s, which isn't really 3 requests/s, because the requests are not parallel and we need to process the data

  data-updater:
    leaderboards:
      cron: "0 */2 * * * *" # every 2 Minutes (But waits for the previous run to finish)
    tracks:
      cron: "0 0 0 * * *" # every day at 0:00

server:
  error:
    include-message: always
    include-exception: false
    include-stacktrace: never
    include-binding-errors: always
  forward-headers-strategy: framework
  servlet:
    context-path: /api

springdoc:
  enable-native-support: true

logging:
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/drl-api-crawler-%d{yyyy-MM-dd}.%i
      max-file-size: 2MB
      total-size-cap: 10MB
      max-history: 10
  level:
    root: info
    de.gregord.drlleaderboardbackend: info
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
#    ch.qos.logback: trace
#    org.springframework: debug
#    org.springframework.transaction: trace
#    org.hibernate.engine.transaction.internal.TransactionImpl: debug
#    org.springframework.orm.jpa: debug

